services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: banco
      POSTGRES_PASSWORD: banco
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banco"]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build: .
    ports: ["8080:8080"]
    environment:
      DB_URL: jdbc:postgresql://db:5432/banco
      DB_USER: banco
      DB_PASSWORD: banco
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:

