CREATE TABLE client (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(120) NOT NULL,
 document varchar(20) NOT NULL UNIQUE CHECK (document ~ '^([0-9]{11}|[A-Z0-9]{12}[0-9]{2})$'),
 email varchar(254) NOT NULL,
 active boolean NOT NULL DEFAULT true
);


CREATE TABLE account (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 client_id bigint NOT NULL REFERENCES client(id),
 account_number bigint NOT NULL,
 check_digit integer NOT NULL,
 label varchar(80) NOT NULL,
 balance numeric(19,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
 status varchar(10) NOT NULL CHECK (status IN ('ACTIVE','CLOSED')),
 CONSTRAINT account_number_digit_unique UNIQUE(account_number,check_digit)
);

CREATE INDEX account_client_idx ON account(client_id);

CREATE TABLE idempotency (
 key varchar(100) PRIMARY KEY,
 account_id bigint NOT NULL,
 destination_account_id bigint,
 operation_type varchar(20) NOT NULL CHECK(operation_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER')),
 amount numeric(19,2) NOT NULL CHECK(amount > 0),
 created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE movement (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id bigint NOT NULL REFERENCES account(id),
 operation_type varchar(20) NOT NULL CHECK(operation_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER_OUT','TRANSFER_IN')),
 amount numeric(19,2) NOT NULL CHECK(amount > 0),
 balance_after numeric(19,2) NOT NULL CHECK(balance_after >= 0),
 idempotency_key varchar(100) NOT NULL REFERENCES idempotency(key),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(idempotency_key,operation_type)
);
CREATE INDEX movement_statement_idx ON movement(account_id,created_at,id);
CREATE TABLE transfer (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 idempotency_key varchar(100) NOT NULL UNIQUE REFERENCES idempotency(key),
 debit_movement_id bigint NOT NULL UNIQUE REFERENCES movement(id),
 credit_movement_id bigint NOT NULL UNIQUE REFERENCES movement(id),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 CHECK(debit_movement_id <> credit_movement_id)
);

